---
services:
  frontend:
    build:
      context: ./authenticator
    ports:
      - 80:80
    networks:
      - archiver
  api:
    image: relayer-api
    build:
      context: .
    command: api
    env_file: .compose.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8989:8989"
    networks:
      - archiver
    volumes:
      - log-data:/var/log/relayer-api
  auth:
    image: relayer-api
    command: auth
    depends_on:
      database:
        condition: service_healthy
    networks:
      - archiver
    volumes:
      - log-data:/var/log/relayer-archiver
  archiver:
    image: relayer-api
    command: archiver
    env_file: .compose.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - archiver
    volumes:
      - log-data:/var/log/relayer-archiver
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    image: postgres
    networks:
      - archiver
    environment:
      POSTGRES_PASSWORD: relayer
      POSTGRES_USER: relayer
      POSTGRES_DB: relayer
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "relayer", "-U", "relayer"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  log-data:
  db-data:
networks:
  archiver: {}
